FROM {{ os_version }}

LABEL maintainer="O1.IO"
{% if system_dependencies|length > 0 %}

RUN {{ package_manager }} update -y && \
    {{ package_manager }} install -y {{ system_dependencies|join(' ') }}
{% endif %}

ENV KAFKA_HOME=/opt/kafka

RUN mkdir -p $KAFKA_HOME && curl -L {{ archive_url }} | tar xzf - --strip-components=1 -C $KAFKA_HOME

ENV PATH $PATH:${KAFKA_HOME}/bin

RUN mkdir /entrypoint.d
COPY entrypoints/10-setup-local-zookeeper.sh entrypoints/20-setup-config.sh entrypoints/30-log4j-config.sh /entrypoint.d/

COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY scripts/start-kafka.sh /usr/bin/start-kafka.sh
RUN chmod +x /usr/bin/start-kafka.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["start-kafka.sh"]
